version: '3.9'
services:
  web-angluar:
    build: ./unit-converter/
    ports:
      - "4201:443"
    volumes:
      - ./certificates:/etc/nginx/cert
  web-react:
    build: ./unit-converter-web/
    ports:
      - "3000:443"
    volumes:
      - ./certificates:/etc/nginx/cert
  api:
    build: ./UnitConverter-Api/UnitConverter.Api/
    ports:
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=qwerty1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx
    volumes:
      - ./certificates:/https:ro